-- V9__insert_weapons.sql
-- Seeds the weapon table from weapon_mapping_with_rarity.json (235 weapons across 5 weapon types)

INSERT INTO weapon (weapon_id, weapon_slug, weapon_name, rarity, wep_type_id)
VALUES
    (1, 'alley-hunter', 'Alley Hunter', 4, 4),
    (2, 'amos-bow', 'Amos'' Bow', 5, 4),
    (3, 'aqua-simulacra', 'Aqua Simulacra', 5, 4),
    (4, 'astral-vultures-crimson-plumage', 'Astral Vulture''s Crimson Plumage', 5, 4),
    (5, 'blackcliff-warbow', 'Blackcliff Warbow', 4, 4),
    (6, 'chain-breaker', 'Chain Breaker', 4, 4),
    (7, 'cloudforged', 'Cloudforged', 4, 4),
    (8, 'compound-bow', 'Compound Bow', 4, 4),
    (9, 'elegy-for-the-end', 'Elegy for the End', 5, 4),
    (10, 'end-of-the-line', 'End of the Line', 4, 4),
    (11, 'fading-twilight', 'Fading Twilight', 4, 4),
    (12, 'favonius-warbow', 'Favonius Warbow', 4, 4),
    (13, 'flower-wreathed-feathers', 'Flower-Wreathed Feathers', 4, 4),
    (14, 'golden-frostbound-oath', 'Golden Frostbound Oath', 5, 4),
    (15, 'hamayumi', 'Hamayumi', 4, 4),
    (16, 'hunters-bow', 'Hunter''s Bow', 1, 4),
    (17, 'hunters-path', 'Hunter''s Path', 5, 4),
    (18, 'ibis-piercer', 'Ibis Piercer', 4, 4),
    (19, 'kings-squire', 'King''s Squire', 4, 4),
    (20, 'messenger', 'Messenger', 3, 4),
    (21, 'mitternachts-waltz', 'Mitternachts Waltz', 4, 4),
    (22, 'mouuns-moon', 'Mouun''s Moon', 4, 4),
    (23, 'polar-star', 'Polar Star', 5, 4),
    (24, 'predator', 'Predator', 4, 4),
    (25, 'prototype-crescent', 'Prototype Crescent', 4, 4),
    (26, 'rainbow-serpents-rain-bow', 'Rainbow Serpent''s Rain Bow', 4, 4),
    (27, 'range-gauge', 'Range Gauge', 4, 4),
    (28, 'raven-bow', 'Raven Bow', 3, 4),
    (29, 'recurve-bow', 'Recurve Bow', 3, 4),
    (30, 'royal-bow', 'Royal Bow', 4, 4),
    (31, 'rust', 'Rust', 4, 4),
    (32, 'sacrificial-bow', 'Sacrificial Bow', 4, 4),
    (33, 'scion-of-the-blazing-sun', 'Scion of the Blazing Sun', 4, 4),
    (34, 'seasoned-hunters-bow', 'Seasoned Hunter''s Bow', 2, 4),
    (35, 'sequence-of-solitude', 'Sequence of Solitude', 4, 4),
    (36, 'sharpshooters-oath', 'Sharpshooter''s Oath', 3, 4),
    (37, 'silvershower-heartstrings', 'Silvershower Heartstrings', 5, 4),
    (38, 'skyward-harp', 'Skyward Harp', 5, 4),
    (39, 'slingshot', 'Slingshot', 3, 4),
    (40, 'snare-hook', 'Snare Hook', 4, 4),
    (41, 'song-of-stillness', 'Song of Stillness', 4, 4),
    (42, 'the-daybreak-chronicles', 'The Daybreak Chronicles', 5, 4),
    (43, 'the-first-great-magic', 'The First Great Magic', 5, 4),
    (44, 'the-stringless', 'The Stringless', 4, 4),
    (45, 'the-viridescent-hunt', 'The Viridescent Hunt', 4, 4),
    (46, 'thundering-pulse', 'Thundering Pulse', 5, 4),
    (47, 'windblume-ode', 'Windblume Ode', 4, 4),
    (48, 'a-thousand-floating-dreams', 'A Thousand Floating Dreams', 5, 5),
    (49, 'amber-catalyst', 'Amber Catalyst', 3, 5),
    (50, 'angelos-heptades', 'Angelos'' Heptades', 5, 5),
    (51, 'apprentices-notes', 'Apprentice''s Notes', 1, 5),
    (52, 'ash-graven-drinking-horn', 'Ash-Graven Drinking Horn', 4, 5),
    (53, 'ballad-of-the-boundless-blue', 'Ballad of the Boundless Blue', 4, 5),
    (54, 'blackcliff-agate', 'Blackcliff Agate', 4, 5),
    (55, 'blackmarrow-lantern', 'Blackmarrow Lantern', 4, 5),
    (56, 'cashflow-supervision', 'Cashflow Supervision', 5, 5),
    (57, 'cranes-echoing-call', 'Crane''s Echoing Call', 5, 5),
    (58, 'dawning-frost', 'Dawning Frost', 4, 5),
    (59, 'dodoco-tales', 'Dodoco Tales', 4, 5),
    (60, 'emerald-orb', 'Emerald Orb', 3, 5),
    (61, 'etherlight-spindlelute', 'Etherlight Spindlelute', 4, 5),
    (62, 'everlasting-moonglow', 'Everlasting Moonglow', 5, 5),
    (63, 'eye-of-perception', 'Eye of Perception', 4, 5),
    (64, 'favonius-codex', 'Favonius Codex', 4, 5),
    (65, 'flowing-purity', 'Flowing Purity', 4, 5),
    (66, 'frostbearer', 'Frostbearer', 4, 5),
    (67, 'fruit-of-fulfillment', 'Fruit of Fulfillment', 4, 5),
    (68, 'hakushin-ring', 'Hakushin Ring', 4, 5),
    (69, 'jadefalls-splendor', 'Jadefall''s Splendor', 5, 5),
    (70, 'kaguras-verity', 'Kagura''s Verity', 5, 5),
    (71, 'lost-prayer-to-the-sacred-winds', 'Lost Prayer to the Sacred Winds', 5, 5),
    (72, 'magic-guide', 'Magic Guide', 3, 5),
    (73, 'mappa-mare', 'Mappa Mare', 4, 5),
    (74, 'memory-of-dust', 'Memory of Dust', 5, 5),
    (75, 'nightweavers-looking-glass', 'Nightweaver''s Looking Glass', 5, 5),
    (76, 'nocturnes-curtain-call', 'Nocturne''s Curtain Call', 5, 5),
    (77, 'oathsworn-eye', 'Oathsworn Eye', 4, 5),
    (78, 'otherworldly-story', 'Otherworldly Story', 3, 5),
    (79, 'pocket-grimoire', 'Pocket Grimoire', 2, 5),
    (80, 'prototype-amber', 'Prototype Amber', 4, 5),
    (81, 'reliquary-of-truth', 'Reliquary of Truth', 5, 5),
    (82, 'ring-of-yaxche', 'Ring of Yaxche', 4, 5),
    (83, 'royal-grimoire', 'Royal Grimoire', 4, 5),
    (84, 'sacrificial-fragments', 'Sacrificial Fragments', 4, 5),
    (85, 'sacrificial-jade', 'Sacrificial Jade', 4, 5),
    (86, 'skyward-atlas', 'Skyward Atlas', 5, 5),
    (87, 'solar-pearl', 'Solar Pearl', 4, 5),
    (88, 'starcallers-watch', 'Starcaller''s Watch', 5, 5),
    (89, 'sunny-morning-sleep-in', 'Sunny Morning Sleep-In', 5, 5),
    (90, 'surfs-up', 'Surf''s Up', 5, 5),
    (91, 'the-widsith', 'The Widsith', 4, 5),
    (92, 'thrilling-tales-of-dragon-slayers', 'Thrilling Tales of Dragon Slayers', 3, 5),
    (93, 'tome-of-the-eternal-flow', 'Tome of the Eternal Flow', 5, 5),
    (94, 'tulaytullahs-remembrance', 'Tulaytullah''s Remembrance', 5, 5),
    (95, 'twin-nephrite', 'Twin Nephrite', 3, 5),
    (96, 'vivid-notions', 'Vivid Notions', 5, 5),
    (97, 'wandering-evenstar', 'Wandering Evenstar', 4, 5),
    (98, 'waveriding-whirl', 'Waveriding Whirl', 4, 5),
    (99, 'wine-and-song', 'Wine and Song', 4, 5),
    (100, 'a-thousand-blazing-suns', 'A Thousand Blazing Suns', 5, 2),
    (101, 'akuoumaru', 'Akuoumaru', 4, 2),
    (102, 'beacon-of-the-reed-sea', 'Beacon of the Reed Sea', 5, 2),
    (103, 'blackcliff-slasher', 'Blackcliff Slasher', 4, 2),
    (104, 'bloodtainted-greatsword', 'Bloodtainted Greatsword', 3, 2),
    (105, 'debate-club', 'Debate Club', 3, 2),
    (106, 'earth-shaker', 'Earth Shaker', 4, 2),
    (107, 'fang-of-the-mountain-king', 'Fang of the Mountain King', 5, 2),
    (108, 'favonius-greatsword', 'Favonius Greatsword', 4, 2),
    (109, 'ferrous-shadow', 'Ferrous Shadow', 3, 2),
    (110, 'flame-forged-insight', 'Flame-Forged Insight', 4, 2),
    (111, 'flame-forged-insight-3d', 'Flame-Forged Insight 3D', 4, 2),
    (112, 'forest-regalia', 'Forest Regalia', 4, 2),
    (113, 'fruitful-hook', 'Fruitful Hook', 4, 2),
    (114, 'gest-of-the-mighty-wolf', 'Gest of the Mighty Wolf', 5, 2),
    (115, 'katsuragikiri-nagamasa', 'Katsuragikiri Nagamasa', 4, 2),
    (116, 'lithic-blade', 'Lithic Blade', 4, 2),
    (117, 'luxurious-sea-lord', 'Luxurious Sea-Lord', 4, 2),
    (118, 'mailed-flower', 'Mailed Flower', 4, 2),
    (119, 'makhaira-aquamarine', 'Makhaira Aquamarine', 4, 2),
    (120, 'master-key', 'Master Key', 4, 2),
    (121, 'old-mercs-pal', 'Old Merc''s Pal', 2, 2),
    (122, 'portable-power-saw', 'Portable Power Saw', 4, 2),
    (123, 'prototype-archaic', 'Prototype Archaic', 4, 2),
    (124, 'quartz', 'Quartz', 3, 2),
    (125, 'rainslasher', 'Rainslasher', 4, 2),
    (126, 'redhorn-stonethresher', 'Redhorn Stonethresher', 5, 2),
    (127, 'royal-greatsword', 'Royal Greatsword', 4, 2),
    (128, 'sacrificial-greatsword', 'Sacrificial Greatsword', 4, 2),
    (129, 'serpent-spine', 'Serpent Spine', 4, 2),
    (130, 'skyrider-greatsword', 'Skyrider Greatsword', 3, 2),
    (131, 'skyward-pride', 'Skyward Pride', 5, 2),
    (132, 'snow-tombed-starsilver', 'Snow-Tombed Starsilver', 4, 2),
    (133, 'song-of-broken-pines', 'Song of Broken Pines', 5, 2),
    (134, 'talking-stick', 'Talking Stick', 4, 2),
    (135, 'the-bell', 'The Bell', 4, 2),
    (136, 'the-unforged', 'The Unforged', 5, 2),
    (137, 'tidal-shadow', 'Tidal Shadow', 4, 2),
    (138, 'ultimate-overlords-mega-magic-sword', 'Ultimate Overlord''s Mega Magic Sword', 4, 2),
    (139, 'verdict', 'Verdict', 5, 2),
    (140, 'waster-greatsword', 'Waster Greatsword', 1, 2),
    (141, 'white-iron-greatsword', 'White Iron Greatsword', 3, 2),
    (142, 'whiteblind', 'Whiteblind', 4, 2),
    (143, 'wolfs-gravestone', 'Wolf''s Gravestone', 5, 2),
    (144, 'ballad-of-the-fjords', 'Ballad of the Fjords', 4, 3),
    (145, 'beginners-protector', 'Beginner''s Protector', 1, 3),
    (146, 'black-tassel', 'Black Tassel', 3, 3),
    (147, 'blackcliff-pole', 'Blackcliff Pole', 4, 3),
    (148, 'bloodsoaked-ruins', 'Bloodsoaked Ruins', 5, 3),
    (149, 'calamity-queller', 'Calamity Queller', 5, 3),
    (150, 'crescent-pike', 'Crescent Pike', 4, 3),
    (151, 'crimson-moons-semblance', 'Crimson Moon''s Semblance', 5, 3),
    (152, 'deathmatch', 'Deathmatch', 4, 3),
    (153, 'dialogues-of-the-desert-sages', 'Dialogues of the Desert Sages', 4, 3),
    (154, 'disaster-and-remorse', 'Disaster and Remorse', 5, 3),
    (155, 'dragons-bane', 'Dragon''s Bane', 4, 3),
    (156, 'dragonspine-spear', 'Dragonspine Spear', 4, 3),
    (157, 'engulfing-lightning', 'Engulfing Lightning', 5, 3),
    (158, 'favonius-lance', 'Favonius Lance', 4, 3),
    (159, 'footprint-of-the-rainbow', 'Footprint of the Rainbow', 4, 3),
    (160, 'fractured-halo', 'Fractured Halo', 5, 3),
    (161, 'halberd', 'Halberd', 3, 3),
    (162, 'iron-point', 'Iron Point', 2, 3),
    (163, 'kitain-cross-spear', 'Kitain Cross Spear', 4, 3),
    (164, 'lithic-spear', 'Lithic Spear', 4, 3),
    (165, 'lumidouce-elegy', 'Lumidouce Elegy', 5, 3),
    (166, 'missive-windspear', 'Missive Windspear', 4, 3),
    (167, 'moonpiercer', 'Moonpiercer', 4, 3),
    (168, 'mountain-bracing-bolt', 'Mountain-Bracing Bolt', 4, 3),
    (169, 'primordial-jade-winged-spear', 'Primordial Jade Winged-Spear', 5, 3),
    (170, 'prospectors-drill', 'Prospector''s Drill', 4, 3),
    (171, 'prospectors-shovel', 'Prospector''s Shovel', 4, 3),
    (172, 'prototype-starglitter', 'Prototype Starglitter', 4, 3),
    (173, 'rightful-reward', 'Rightful Reward', 4, 3),
    (174, 'royal-spear', 'Royal Spear', 4, 3),
    (175, 'sacrificers-staff', 'Sacrificer''s Staff', 4, 3),
    (176, 'skyward-spine', 'Skyward Spine', 5, 3),
    (177, 'staff-of-homa', 'Staff of Homa', 5, 3),
    (178, 'staff-of-the-scarlet-sands', 'Staff of the Scarlet Sands', 5, 3),
    (179, 'symphonist-of-scents', 'Symphonist of Scents', 5, 3),
    (180, 'tamayuratei-no-ohanashi', 'Tamayuratei no Ohanashi', 4, 3),
    (181, 'the-catch', 'The Catch', 4, 3),
    (182, 'vortex-vanquisher', 'Vortex Vanquisher', 5, 3),
    (183, 'wavebreakers-fin', 'Wavebreaker''s Fin', 4, 3),
    (184, 'white-tassel', 'White Tassel', 3, 3),
    (185, 'absolution', 'Absolution', 5, 1),
    (186, 'amenoma-kageuchi', 'Amenoma Kageuchi', 4, 1),
    (187, 'aquila-favonia', 'Aquila Favonia', 5, 1),
    (188, 'athame-artis', 'Athame Artis', 5, 1),
    (189, 'azurelight', 'Azurelight', 5, 1),
    (190, 'blackcliff-longsword', 'Blackcliff Longsword', 4, 1),
    (191, 'calamity-of-eshu', 'Calamity of Eshu', 4, 1),
    (192, 'cinnabar-spindle', 'Cinnabar Spindle', 4, 1),
    (193, 'cool-steel', 'Cool Steel', 3, 1),
    (194, 'dark-iron-sword', 'Dark Iron Sword', 3, 1),
    (195, 'dull-blade', 'Dull Blade', 1, 1),
    (196, 'favonius-sword', 'Favonius Sword', 4, 1),
    (197, 'festering-desire', 'Festering Desire', 4, 1),
    (198, 'fillet-blade', 'Fillet Blade', 3, 1),
    (199, 'finale-of-the-deep', 'Finale of the Deep', 4, 1),
    (200, 'fleuve-cendre-ferryman', 'Fleuve Cendre Ferryman', 4, 1),
    (201, 'flute-of-ezpitzal', 'Flute of Ezpitzal', 4, 1),
    (202, 'freedom-sworn', 'Freedom-Sworn', 5, 1),
    (203, 'haran-geppaku-futsu', 'Haran Geppaku Futsu', 5, 1),
    (204, 'harbinger-of-dawn', 'Harbinger of Dawn', 3, 1),
    (205, 'iron-sting', 'Iron Sting', 4, 1),
    (206, 'kagotsurube-isshin', 'Kagotsurube Isshin', 4, 1),
    (207, 'key-of-khaj-nisut', 'Key of Khaj-Nisut', 5, 1),
    (208, 'light-of-foliar-incision', 'Light of Foliar Incision', 5, 1),
    (209, 'lightbearing-moonshard', 'Lightbearing Moonshard', 5, 1),
    (210, 'lions-roar', 'Lion''s Roar', 4, 1),
    (211, 'mistsplitter-reforged', 'Mistsplitter Reforged', 5, 1),
    (212, 'moonweavers-dawn', 'Moonweaver''s Dawn', 4, 1),
    (213, 'peak-patrol-song', 'Peak Patrol Song', 5, 1),
    (214, 'primordial-jade-cutter', 'Primordial Jade Cutter', 5, 1),
    (215, 'prototype-rancour', 'Prototype Rancour', 4, 1),
    (216, 'royal-longsword', 'Royal Longsword', 4, 1),
    (217, 'sacrificial-sword', 'Sacrificial Sword', 4, 1),
    (218, 'sapwood-blade', 'Sapwood Blade', 4, 1),
    (219, 'serenitys-call', 'Serenity''s Call', 4, 1),
    (220, 'silver-sword', 'Silver Sword', 2, 1),
    (221, 'skyrider-sword', 'Skyrider Sword', 3, 1),
    (222, 'skyward-blade', 'Skyward Blade', 5, 1),
    (223, 'splendor-of-tranquil-waters', 'Splendor of Tranquil Waters', 5, 1),
    (224, 'sturdy-bone', 'Sturdy Bone', 4, 1),
    (225, 'summit-shaper', 'Summit Shaper', 5, 1),
    (226, 'sword-of-descension', 'Sword of Descension', 4, 1),
    (227, 'the-alley-flash', 'The Alley Flash', 4, 1),
    (228, 'the-black-sword', 'The Black Sword', 4, 1),
    (229, 'the-dockhands-assistant', 'The Dockhand''s Assistant', 4, 1),
    (230, 'the-flute', 'The Flute', 4, 1),
    (231, 'toukabou-shigure', 'Toukabou Shigure', 4, 1),
    (232, 'travelers-handy-sword', 'Traveler''s Handy Sword', 3, 1),
    (233, 'uraku-misugiri', 'Uraku Misugiri', 5, 1),
    (234, 'wolf-fang', 'Wolf-Fang', 4, 1),
    (235, 'xiphos-moonlight', 'Xiphos'' Moonlight', 4, 1);
