-- V10__insert_artifact_sets.sql
-- Seeds the artifact_set table from artifact_mapping.json (55 artifact sets)

INSERT INTO artifact_set (artifact_set_id, artifact_set_slug, artifact_set_name)
VALUES
    (1, 'a-day-carved-from-rising-winds', 'A Day Carved From Rising Winds'),
    (2, 'adventurer', 'Adventurer'),
    (3, 'archaic-petra', 'Archaic Petra'),
    (4, 'aubade-of-morningstar-and-moon', 'Aubade of Morningstar and Moon'),
    (5, 'berserker', 'Berserker'),
    (6, 'blizzard-strayer', 'Blizzard Strayer'),
    (7, 'bloodstained-chivalry', 'Bloodstained Chivalry'),
    (8, 'brave-heart', 'Brave Heart'),
    (9, 'celestial-gift', 'Celestial Gift'),
    (10, 'crimson-witch-of-flames', 'Crimson Witch of Flames'),
    (11, 'deepwood-memories', 'Deepwood Memories'),
    (12, 'defenders-will', 'Defender''s Will'),
    (13, 'desert-pavilion-chronicle', 'Desert Pavilion Chronicle'),
    (14, 'disenchantment-in-deep-shadow', 'Disenchantment in Deep Shadow'),
    (15, 'echoes-of-an-offering', 'Echoes of an Offering'),
    (16, 'emblem-of-severed-fate', 'Emblem of Severed Fate'),
    (17, 'finale-of-the-deep-galleries', 'Finale of the Deep Galleries'),
    (18, 'flower-of-paradise-lost', 'Flower of Paradise Lost'),
    (19, 'fragment-of-harmonic-whimsy', 'Fragment of Harmonic Whimsy'),
    (20, 'gambler', 'Gambler'),
    (21, 'gilded-dreams', 'Gilded Dreams'),
    (22, 'gladiators-finale', 'Gladiator''s Finale'),
    (23, 'golden-troupe', 'Golden Troupe'),
    (24, 'heart-of-depth', 'Heart of Depth'),
    (25, 'husk-of-opulent-dreams', 'Husk of Opulent Dreams'),
    (26, 'instructor', 'Instructor'),
    (27, 'lavawalker', 'Lavawalker'),
    (28, 'long-nights-oath', 'Long Night''s Oath'),
    (29, 'lucky-dog', 'Lucky Dog'),
    (30, 'maiden-beloved', 'Maiden Beloved'),
    (31, 'marechaussee-hunter', 'Marechaussee Hunter'),
    (32, 'martial-artist', 'Martial Artist'),
    (33, 'night-of-the-skys-unveiling', 'Night of the Sky''s Unveiling'),
    (34, 'nighttime-whispers-in-the-echoing-woods', 'Nighttime Whispers in the Echoing Woods'),
    (35, 'noblesse-oblige', 'Noblesse Oblige'),
    (36, 'nymphs-dream', 'Nymph''s Dream'),
    (37, 'obsidian-codex', 'Obsidian Codex'),
    (38, 'ocean-hued-clam', 'Ocean-Hued Clam'),
    (39, 'pale-flame', 'Pale Flame'),
    (40, 'resolution-of-sojourner', 'Resolution of Sojourner'),
    (41, 'retracing-bolide', 'Retracing Bolide'),
    (42, 'scholar', 'Scholar'),
    (43, 'shimenawas-reminiscence', 'Shimenawa''s Reminiscence'),
    (44, 'silken-moons-serenade', 'Silken Moon''s Serenade'),
    (45, 'song-of-days-past', 'Song of Days Past'),
    (46, 'tenacity-of-the-millelith', 'Tenacity of the Millelith'),
    (47, 'the-exile', 'The Exile'),
    (48, 'thundering-fury', 'Thundering Fury'),
    (49, 'thundersoother', 'Thundersoother'),
    (50, 'tiny-miracle', 'Tiny Miracle'),
    (51, 'traveling-doctor', 'Traveling Doctor'),
    (52, 'unfinished-reverie', 'Unfinished Reverie'),
    (53, 'vermillion-hereafter', 'Vermillion Hereafter'),
    (54, 'viridescent-venerer', 'Viridescent Venerer'),
    (55, 'wanderers-troupe', 'Wanderer''s Troupe');
